f_obj = open("file2.txt", "r")
content = f_obj.readlines()
lines = len(content)
print("Number of lines in the file is " + str(lines))
f_obj = open("file2.txt", "r")
content = f_obj.read()
content = content.split()
print(f'Общее количество слов - {len(content)}')
f_obj.close()
